### ISSUE TITLE
containerized predictions fail due to permissions in the container

### ISSUE THREAD

**Issue by dvitale199** [dvitale199/GenoTools#141]
**Describe the bug**
when attempting to run containerized predictions, a user with an unknown OS encountered the following error:

```
Getting Common SNPs

/usr/local/lib/python3.10/dist-packages/genotools/utils.py:404: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.

  bim1 = pd.read_csv(f'{geno_path1}.bim', sep='\t', header=None)

Traceback (most recent call last):

  File "/usr/local/bin/genotools", line 8, in <module>

    sys.exit(handle_main())

  File "/usr/local/lib/python3.10/dist-packages/genotools/__main__.py", line 152, in handle_main

    out_dict = execute_pipeline(run_steps_list, ordered_steps, args_dict['geno_path'], args_dict['out'], samp_qc=samp_qc, var_qc=var_qc, ancestry=ancestry, assoc=assoc, args=args_dict, tmp_dir=tmp_dir)

  File "/usr/local/lib/python3.10/dist-packages/genotools/pipeline.py", line 128, in execute_pipeline

    out_dict[step] = steps_dict[step]()

  File "/usr/local/lib/python3.10/dist-packages/genotools/ancestry.py", line 1103, in run_ancestry

    trained_clf, pred = self.get_containerized_predictions(

  File "/usr/local/lib/python3.10/dist-packages/genotools/ancestry.py", line 681, in get_containerized_predictions

    X_test.to_csv(f'{container_dir}/X_test.txt', sep='\t', index=False)

  File "/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py", line 3772, in to_csv

    return DataFrameRenderer(formatter).to_csv(

  File "/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py", line 1186, in to_csv

    csv_formatter.save()

  File "/usr/local/lib/python3.10/dist-packages/pandas/io/formats/csvs.py", line 240, in save

    with get_handle(

  File "/usr/local/lib/python3.10/dist-packages/pandas/io/common.py", line 859, in get_handle

    handle = open(

PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.10/dist-packages/genotools/container/X_test.txt'
```

**To Reproduce**
Steps to reproduce the behavior (NA if not applicable). Can include commands that were run:
user attempted to run:
```
genotools \
--pfile /path/to/genotypes/for/qc \
--out /path/to/qc/output \
--ancestry \
--ref_panel /path/to/reference/panel \
--ref_labels /path/to/reference/ancestry/labels \
--all_sample \
--all_variant
--container
```
**Expected behavior**
predictions should be assigned via a model that is copied over to the container

**Desktop (please complete the following information):**
 - OS: 
 - Version 1.0.0
- Python version: 3.10

**Additional context**
This is expected to be a result of processes being run in an hpc system that does not have docker available. the --singularity option should solve this if singularity is available on the system, otherwise user will have to train a new model locally using the base command:

```
genotools \
--pfile /path/to/genotypes/for/qc \
--out /path/to/qc/output \
--ancestry \
--ref_panel /path/to/reference/panel \
--ref_labels /path/to/reference/ancestry/labels \
--all_sample \
--all_variant
```

**Comment by dvitale199** [comment]
Closing as obsolete: 2.x removed this execution path rather than fixing it.

`--container`, `--singularity` and `--cloud` are now rejected at argument-parsing
time (`genotools/cli/parser.py`, `_UNSUPPORTED_INFERENCE_FLAGS`) with an
explanatory error rather than running.

The reason is that the containers were built around a 1.x `umap_linearsvc`
pickle, and 2.0's `AncestryModel.load` cannot read that format by design. So
there is nothing inside the container left to fix — honouring the flag would
require a rebuilt, republished image carrying a 2.0-format model, which does not
exist.

What to do instead:

- **Predict locally.** Drop the flag. `genotools-download` now serves
  `nba_gp2_r12`, a 2.x-format model, so `--model` works without a container.
- **Stay on 1.x.** Pin `genotools<2.0` to keep the old container path.

See [MIGRATION_2.0.md](https://github.com/dvitale199/GenoTools/blob/main/MIGRATION_2.0.md).
